services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: argos_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./storage:/var/www/storage
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - argos_network

  nginx:
    image: nginx:1.25-alpine
    container_name: argos_nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - argos_network

  postgres:
    image: postgres:16
    container_name: argos_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: argos
      POSTGRES_USER: argos_user
      POSTGRES_PASSWORD: password123
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U argos_user -d argos"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - argos_network

  redis:
    image: redis:7-alpine
    container_name: argos_redis
    restart: unless-stopped
    command: redis-server --appendonly yes --requirepass redis_password123
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "redis_password123", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - argos_network

  queue:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: argos_queue
    restart: unless-stopped
    working_dir: /var/www
    command: php artisan queue:work redis --sleep=3 --tries=3 --timeout=90
    volumes:
      - .:/var/www
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - argos_network

  reverb:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: argos_reverb
    restart: unless-stopped
    working_dir: /var/www
    command: php artisan reverb:start --host=0.0.0.0 --port=8080
    ports:
      - "6001:8080"
    volumes:
      - .:/var/www
    depends_on:
      - app
      - redis
    networks:
      - argos_network

volumes:
  postgres_data:
  redis_data:

networks:
  argos_network:
    driver: bridge